apiVersion : apps/v1
kind: Deployment
metadata:
  name: adminportalproduction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminportalproduction
  template:
    metadata:
      labels:
        app: adminportalproduction
    spec:
      containers:
        - name: adminportalproduction
          image: containerregistrymwsproduction.azurecr.io/adminportalproduction
          ports:
          - containerPort: 80
