apiVersion : apps/v1
kind: Deployment
metadata:
  name: adminportaldevelopment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminportaldevelopment
  template:
    metadata:
      labels:
        app: adminportaldevelopment 
    spec:
      containers:
        - name: adminportaldevelopment 
          image: containerregistrymwsdevelopment.azurecr.io/adminportaldevelopment
          ports:
          - containerPort: 80
          env:
            - name: API_URL
              value: "https://sls-weur-dev-mws-admin-portal.azurewebsites.net/api"
            - name: X_FUNCTIONS_KEY
              value: "JOFewtUZYA0am9x96rh2bCICa58qwIa0OuMa75jo1aITlSBJAErkXw"
